name: Build unity plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        
    steps:
    - uses: actions/checkout@v2
    # - name: Setup Android NDK
    #   uses: nttld/setup-ndk@v1
    #   id: setup-ndk
    #   with:
    #     ndk-version: r21e
    #     add-to-path: false
    #     local-cache: true
    # - name: check the dir
    #   run: |
    #         cd $ANDROID_NDK_HOME
    #         ls
    #   env:
        # ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      
    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
            
    - name: make
      run: bash Utils/build-all-platforms.sh  --type full --version 2.1  --no-android --no-ios --no-macos
      # env:
      #   ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
